/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // ── API Reference ──────────────────────────────────────────────────────
  // Auto-generated by TypeDoc into docs/api/. Uses filesystem-based sidebar.
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],

  // ── Architecture ───────────────────────────────────────────────────────
  // Hand-curated pages with embedded Mermaid diagrams and rendered SVGs.
  architectureSidebar: [
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/index',
      ],
    },
  ],

  // ── UI Previews ────────────────────────────────────────────────────────
  // Screenshot gallery generated by capture-ui.mjs.
  previewsSidebar: [
    {
      type: 'category',
      label: 'UI Previews',
      items: [
        'previews/index',
      ],
    },
  ],
};

module.exports = sidebars;
