name: "Bug Report"
description: "Report a bug in Market Data Bridge"
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: "Clear description of the bug"
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: "Minimal steps to trigger the bug"
      placeholder: |
        1. Start the bridge with `npm run dev`
        2. Navigate to http://localhost:3001/evals
        3. Click on an eval row
        4. See error in console
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "What should happen"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "What actually happens (include error messages, screenshots)"
    validations:
      required: true

  - type: dropdown
    id: subsystem
    attributes:
      label: Subsystem
      options:
        - IBKR Connection
        - Order Execution
        - Eval Engine
        - Dashboard (Frontend)
        - REST API
        - MCP Tools
        - Risk Gate / Session
        - Holly AI
        - Scheduler
        - Database
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "Critical — execution-critical (orders, risk, connection)"
        - "High — data loss or incorrect calculations"
        - "Medium — feature broken but workaround exists"
        - "Low — cosmetic or minor"
    validations:
      required: true
