import fs from "fs/promises";
import path from "path";
import { logger } from "../logging.js";

const log = logger.child({ subsystem: "holly-exit" });

export interface BaselineMetrics {
  win_rate: number;
  avg_pnl: number;
  total_pnl: number;
}

export interface OptimizedMetrics {
  win_rate: number;
  avg_pnl: number;
  total_pnl: number;
  profit_factor: number;
  sharpe: number;
  max_drawdown: number;
  avg_hold_minutes: number;
}

export interface StrategyExitConfig {
  direction: string;
  trade_count: number;
  exit_rule: string;
  params: Record<string, number>;
  baseline: BaselineMetrics;
  optimized: OptimizedMetrics;
}

export interface ExitParamsData {
  generated_at: string;
  data_range: string;
  total_trades_analyzed: number;
  polygon_tier: string;
  baseline_avg_pnl: number;
  baseline_total_pnl: number;
  strategies: Record<string, StrategyExitConfig>;
}

let cachedParams: ExitParamsData | null = null;
let lastLoadTime = 0;
const CACHE_TTL_MS = 1000 * 60 * 60; // 1 hour

/**
 * Loads the optimal exit parameters generated by the offline analytics pipeline.
 * Caches the result in memory.
 */
export async function getExitParams(): Promise<ExitParamsData> {
  const now = Date.now();
  if (cachedParams && (now - lastLoadTime) < CACHE_TTL_MS) {
    return cachedParams;
  }

  const filePath = path.resolve(process.cwd(), "analytics/holly_exit/output/optimal_exit_params.json");

  try {
    const data = await fs.readFile(filePath, "utf-8");
    cachedParams = JSON.parse(data) as ExitParamsData;
    lastLoadTime = now;
    log.info({ strategiesCount: Object.keys(cachedParams.strategies).length }, "Loaded optimal exit params");
    return cachedParams;
  } catch (error: any) {
    log.error({ err: error, path: filePath }, "Failed to load exit params");
    throw new Error(`Failed to load exit params: ${error.message}`);
  }
}

/**
 * Gets the exit configuration for a specific strategy name.
 */
export async function getStrategyExitConfig(strategyName: string): Promise<StrategyExitConfig | null> {
  const data = await getExitParams();
  return data.strategies[strategyName] || null;
}
